services:
  - type: web
    name: tee-time-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    postBuildCommand: playwright install
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
